services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jokumer\FalManja\:
    resource: '../Classes/*'

  Jokumer\FalManja\Service\ManjaService:
    autowire: false
    public: true

  Jokumer\FalManja\EventListener\BeforeResourceStorageInitializationEventListener:
    tags:
    - name: event.listener
      event: TYPO3\CMS\Core\Resource\Event\BeforeResourceStorageInitializationEvent
  
